[tool.poetry]
name = "essi21"
version = "0.1.1"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8,<3.10"
numpy = "^1.20.3"
pandas = "^1.2.4"
rasterio = "^1.2.4"
jupyter = "^1.0.0"
matplotlib = "^3.4.2"
imageio = "^2.9.0"

[tool.poetry.dev-dependencies]
snakeviz = "^2.1.0"
black = "^21.6b0"
pylint = "^2.8.3"
pytest = "^6.2.4"

[tool.black]
line-length=79
exclude="config.py"

[tool.pylint.reports]
output-format="colorized"
reports="y"
include-ids="yes"
disable=["R0913","C0103"]
msg-template="{msg_id}:{line:3d},{column}: {obj}: {msg}"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
